package chapter1.p08;

import java.util.Deque;

public class Generator implements Runnable{
	
	private Deque<Event> deque;
	public Generator(Deque<Event> deque) {
		this.deque = deque;
	}
	
	@Override
	public void run() {

		try {
			while(true) {
				Event event = new Event(String.format("generated by %s",Thread.currentThread().getName()));
				synchronized(this) {
					deque.addLast(event);
					System.out.println(deque.size()+"	"+event);
				}
				Thread.sleep(1000);
			}
		} catch (InterruptedException e) {
			throw new RuntimeException(e);
		}
	}
}
